    name: AntiHung
    main: feed\Loader
    version: 1.0.0
    api: 1.12.0

    permission:
        feedme.feed:
            description: "Berechtigung zum fuettern"
            default: op
            children:
                feedme.other:
                    description: "Berechtigung andere zu fuettern"
                    default: op
