    name: feed
    main: feed\Loader
    version: 1.0.0
    api: 1.12.0

    permission:
        feedme.feed:
            description: "Feed that face permission"
            default: op
            children:
                feedme.other:
                    description: "Feed others face permission"
                    default: op
