    name: feed
    main: feed\Loader
    version: 0.0.9
    api: 1.12.0
    
    commands:
     feed:
        description: "Feed that face!"
        usage: "/feed (Player)"
        permission: feedme.feed
        
    permission:
        feedme.feed:
            description: "Feed that face permission"
            default: op
            children:
                feedme.other:
                    description: "Feed others face permission"
                    default: op
